options:
    version:
        type: string
        description: CockroachDB version to use.
        default: v19.2.2
    default-zone-replicas:
        type: int
        description: The number of replicas to configure for the default replication zone. Using 0 means that the charm will use cluster defaults (see https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables).
        default: 0
    system-data-replicas:
        type: int
        description: The number of replicas to configure for the internal system data. Using 0 means that the charm will use cluster defaults (see https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables)
        default: 0
